# Generated by Django 4.2 on 2025-04-08 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('especialidade', models.CharField(choices=[('pediatra', 'PEDIATRA'), ('dentista', 'DENTISTA'), ('cirurgião', 'CIRURGIÃO'), ('car', 'CAR')], max_length=12)),
                ('crm', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'agendado'), ('REALIZADO', 'realizado'), ('CANCELADO', 'cancelado')], max_length=12)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
