# Generated by Django 4.2 on 2025-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('pediatra', 'PEDIATRA'), ('dentista', 'DENTISTA'), ('cirurgião', 'CIRURGIÃO'), ('CAR', 'CAR')], max_length=12),
        ),
    ]
